packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  diff@<8.0.3: '>=8.0.3'
  tar-fs@>=3.0.0 <3.0.7: '>=3.0.7'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tmp@<=0.2.3: '>=0.2.4'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
