export const xThemes = {
    Primary: 'primary',
    Secondary: 'secondary',
    Success: 'success',
    Info: 'info',
    Warning: 'warning',
    Danger: 'danger',
    Grayscale: 'neutral'
  },

  xVariants = {
    Default: '',
    Outlined: 'outlined',
    Filled: 'filled',
    Raised: 'raised',
    Small: 'small',
    Normal: 'normal',
    Large: 'large'
  },

  AUTO_COMPLETE_NAME = 'autocomplete',
  AUTO_FOCUS_NAME = 'autofocus',
  CHECKED_NAME = 'checked',
  CLASSNAME_TO_TOGGLE_NAME = 'classNameToToggle',
  CLASSNAME_TO_TOGGLE_TARGET_NAME = 'classNameToToggleTarget',
  CLASSNAME_TO_TOGGLE_TARGET_SELECTOR_NAME = `${CLASSNAME_TO_TOGGLE_TARGET_NAME}Selector`,
  DEFAULT_CHECKED_NAME = 'defaultChecked',
  DISABLED_NAME = 'disabled',
  FORM_NAME = 'form',
  INTERSECTING_TARGET_NAME = 'intersectingTarget',
  INTERSECTING_TARGET_SELECTOR_NAME = `${INTERSECTING_TARGET_NAME}Selector`,
  MULTIPLE_NAME = 'multiple',
  NAME_NAME = 'name',
  OBSERVER_CALLBACK = 'observerCallback',
  REQUIRED_NAME = 'required',
  REVERSE_NAME = 'reverse',
  ROOT_MARGIN_NAME = 'rootMargin',
  ROOT_NAME = 'root',
  ROOT_SELECTOR_NAME = 'rootSelector',
  SIZE_NAME = 'size',
  THEME_NAME = 'theme',
  THRESHOLD_NAME = 'threshold',
  TOGGLE_TARGET_NAME = 'toggleTarget',
  TRIGGER_NAME = 'trigger',
  TRIGGER_SELECTOR_NAME = 'triggerSelector',
  VARIETY_NAME = 'variety',
  VALUE_NAME = 'value'
;
